androidSDKPath: C:\Users\osas2\AppData\Local\Android\Sdk
pythonScriptsPath: C:\Users\osas2\Documents\avt\trace-replayer\lib\python-scripts
aaptPath: C:\Users\osas2\AppData\Local\Android\Sdk\build-tools\35.0.0
apkPath: C:\Users\osas2\Documents\avt\apks\klar-125.3.0-x86.apk
getEventFile: C:\Users\osas2\Documents\avt\traces\[02.09.20]getevent.log
outputFolder: C:\Users\osas2\Documents\avt\output
avdPort: 5554
adbPort: 5037
executionNum: 1